import os
import subprocess
from setuptools import setup

ROOT_DIR = os.path.dirname(__file__)
SOURCE_DIR = os.path.join(ROOT_DIR)

# Fetch version from git tags, and write to version.py.
# Also, when git is not available (PyPi package), use stored version.py.
version_py = os.path.join(os.path.dirname(__file__), 'version.py')

install_requires = [
    'pyyaml>=4.2b1'
]

try:
    import importlib
except ImportError:
    install_requires.append('importlib')

try:
    p = subprocess.Popen(['git', 'describe'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    o = p.communicate()
    if p.returncode != 0:
        raise Exception('git describe failed to execute reason: %s' % o[1])
    version_git = o[0].rstrip()
except:
    version_git = open(version_py).read().strip().split('=')[-1].replace('"', '')

version_msg = "# Do not edit this file, versions governed by git tags"
with open(version_py, 'w') as fh:
    fh.write(version_msg + os.linesep + "__version__=" + version_git)

setup(name='libkplug',
      version="{ver}".format(ver=version_git),
      description='Plugable Project Framework',
      author='Kegan Holtzhausen',
      author_email='Kegan.Holtzhausen@kindredgroup.com',
      packages=[
          'libkplug',
          'libksettings'
      ],
      setup_requires=[
          'nose2==0.8.0'
      ],
      tests_require=[
          'unittest2==1.1.0'
      ],
      install_requires=install_requires,
    )